// This file is autogenerated by the hyperschema compiler
// Schema Version: 3
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 3

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @mesh-contact/transport-descriptor
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.transportKind)
    c.string.preencode(state, m.contactSeam)
    c.string.preencode(state, m.transportRole)
    c.string.preencode(state, m.scope)
    state.end++ // max flag is 32 so always one byte
  },
  encode(state, m) {
    const flags =
      (m.scaffoldTransport ? 1 : 0) |
      (m.compatibilityAlias ? 2 : 0) |
      (m.productionPreferred ? 4 : 0) |
      (m.operatorSupplied ? 8 : 0) |
      (m.portExposureRequired ? 16 : 0) |
      (m.participantContact ? 32 : 0)

    c.string.encode(state, m.transportKind)
    c.string.encode(state, m.contactSeam)
    c.string.encode(state, m.transportRole)
    c.string.encode(state, m.scope)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      transportKind: r0,
      contactSeam: r1,
      transportRole: r2,
      scope: r3,
      scaffoldTransport: (flags & 1) !== 0,
      compatibilityAlias: (flags & 2) !== 0,
      productionPreferred: (flags & 4) !== 0,
      operatorSupplied: (flags & 8) !== 0,
      portExposureRequired: (flags & 16) !== 0,
      participantContact: (flags & 32) !== 0
    }
  }
}

// @mesh-contact/readiness-evidence
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.readinessScope)
    state.end++ // max flag is 2 so always one byte
  },
  encode(state, m) {
    const flags = (m.distributedReadinessClaimed ? 1 : 0) | (m.serviceBackendClaimed ? 2 : 0)

    c.string.encode(state, m.readinessScope)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      readinessScope: r0,
      distributedReadinessClaimed: (flags & 1) !== 0,
      serviceBackendClaimed: (flags & 2) !== 0
    }
  }
}

// @mesh-contact/contact-proof-request
const encoding2 = {
  preencode(state, m) {
    c.string.preencode(state, m.requestId)
    c.string.preencode(state, m.participant)
    c.string.preencode(state, m.capability)
    c.string.preencode(state, m.input)
  },
  encode(state, m) {
    c.string.encode(state, m.requestId)
    c.string.encode(state, m.participant)
    c.string.encode(state, m.capability)
    c.string.encode(state, m.input)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)

    return {
      requestId: r0,
      participant: r1,
      capability: r2,
      input: r3
    }
  }
}

// @mesh-contact/contact-proof-response
const encoding3 = {
  preencode(state, m) {
    c.string.preencode(state, m.responseId)
    c.string.preencode(state, m.requestId)
    c.string.preencode(state, m.participant)
    c.string.preencode(state, m.capability)
    c.string.preencode(state, m.received)
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = m.ok ? 1 : 0

    c.string.encode(state, m.responseId)
    c.string.encode(state, m.requestId)
    c.string.encode(state, m.participant)
    c.string.encode(state, m.capability)
    c.string.encode(state, m.received)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      responseId: r0,
      requestId: r1,
      participant: r2,
      capability: r3,
      received: r4,
      ok: (flags & 1) !== 0
    }
  }
}

// @mesh-contact/contact-proof-evidence.selectedTransport
const encoding4_17 = c.frame(encoding0)
// @mesh-contact/contact-proof-evidence.readinessEvidence
const encoding4_18 = c.frame(encoding1)

// @mesh-contact/contact-proof-evidence
const encoding4 = {
  preencode(state, m) {
    const flags =
      (m.contactAttempted ? 1 : 0) |
      (m.contactSucceeded ? 2 : 0) |
      (m.distributedReadinessClaimed ? 4 : 0) |
      (m.elapsedMs ? 8 : 0) |
      (m.failureClass ? 16 : 0) |
      (m.failureMessage ? 32 : 0) |
      ((version >= 2 && m.capabilityDescriptor) ? 64 : 0) |
      ((version >= 3 && m.capabilityAdvertisement) ? 128 : 0)

    c.string.preencode(state, m.artifactKind)
    c.string.preencode(state, m.schema)
    c.string.preencode(state, m.protocolFamily)
    c.string.preencode(state, m.protocolSchema)
    c.string.preencode(state, m.requestEncoding)
    c.string.preencode(state, m.responseEncoding)
    c.string.preencode(state, m.dispatchCommand)
    c.string.preencode(state, m.proofKind)
    c.string.preencode(state, m.transportKind)
    c.string.preencode(state, m.contactSeam)
    c.string.preencode(state, m.participantA)
    c.string.preencode(state, m.participantB)
    c.string.preencode(state, m.operation)
    c.string.preencode(state, m.methodName)
    c.string.preencode(state, m.requestId)
    c.string.preencode(state, m.responseId)
    c.string.preencode(state, m.hostPublicKey)
    encoding4_17.preencode(state, m.selectedTransport)
    encoding4_18.preencode(state, m.readinessEvidence)
    c.uint.preencode(state, flags)

    if (m.elapsedMs) c.uint.preencode(state, m.elapsedMs)
    if (m.failureClass) c.string.preencode(state, m.failureClass)
    if (m.failureMessage) c.string.preencode(state, m.failureMessage)
    if (version >= 2 && m.capabilityDescriptor) encoding4_25.preencode(state, m.capabilityDescriptor)
    if (version >= 3 && m.capabilityAdvertisement) encoding4_26.preencode(state, m.capabilityAdvertisement)
  },
  encode(state, m) {
    const flags =
      (m.contactAttempted ? 1 : 0) |
      (m.contactSucceeded ? 2 : 0) |
      (m.distributedReadinessClaimed ? 4 : 0) |
      (m.elapsedMs ? 8 : 0) |
      (m.failureClass ? 16 : 0) |
      (m.failureMessage ? 32 : 0) |
      ((version >= 2 && m.capabilityDescriptor) ? 64 : 0) |
      ((version >= 3 && m.capabilityAdvertisement) ? 128 : 0)

    c.string.encode(state, m.artifactKind)
    c.string.encode(state, m.schema)
    c.string.encode(state, m.protocolFamily)
    c.string.encode(state, m.protocolSchema)
    c.string.encode(state, m.requestEncoding)
    c.string.encode(state, m.responseEncoding)
    c.string.encode(state, m.dispatchCommand)
    c.string.encode(state, m.proofKind)
    c.string.encode(state, m.transportKind)
    c.string.encode(state, m.contactSeam)
    c.string.encode(state, m.participantA)
    c.string.encode(state, m.participantB)
    c.string.encode(state, m.operation)
    c.string.encode(state, m.methodName)
    c.string.encode(state, m.requestId)
    c.string.encode(state, m.responseId)
    c.string.encode(state, m.hostPublicKey)
    encoding4_17.encode(state, m.selectedTransport)
    encoding4_18.encode(state, m.readinessEvidence)
    c.uint.encode(state, flags)

    if (m.elapsedMs) c.uint.encode(state, m.elapsedMs)
    if (m.failureClass) c.string.encode(state, m.failureClass)
    if (m.failureMessage) c.string.encode(state, m.failureMessage)
    if (version >= 2 && m.capabilityDescriptor) encoding4_25.encode(state, m.capabilityDescriptor)
    if (version >= 3 && m.capabilityAdvertisement) encoding4_26.encode(state, m.capabilityAdvertisement)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.string.decode(state)
    const r5 = c.string.decode(state)
    const r6 = c.string.decode(state)
    const r7 = c.string.decode(state)
    const r8 = c.string.decode(state)
    const r9 = c.string.decode(state)
    const r10 = c.string.decode(state)
    const r11 = c.string.decode(state)
    const r12 = c.string.decode(state)
    const r13 = c.string.decode(state)
    const r14 = c.string.decode(state)
    const r15 = c.string.decode(state)
    const r16 = c.string.decode(state)
    const r17 = encoding4_17.decode(state)
    const r18 = encoding4_18.decode(state)
    const flags = c.uint.decode(state)

    return {
      artifactKind: r0,
      schema: r1,
      protocolFamily: r2,
      protocolSchema: r3,
      requestEncoding: r4,
      responseEncoding: r5,
      dispatchCommand: r6,
      proofKind: r7,
      transportKind: r8,
      contactSeam: r9,
      participantA: r10,
      participantB: r11,
      operation: r12,
      methodName: r13,
      requestId: r14,
      responseId: r15,
      hostPublicKey: r16,
      selectedTransport: r17,
      readinessEvidence: r18,
      contactAttempted: (flags & 1) !== 0,
      contactSucceeded: (flags & 2) !== 0,
      distributedReadinessClaimed: (flags & 4) !== 0,
      elapsedMs: (flags & 8) !== 0 ? c.uint.decode(state) : 0,
      failureClass: (flags & 16) !== 0 ? c.string.decode(state) : null,
      failureMessage: (flags & 32) !== 0 ? c.string.decode(state) : null,
      capabilityDescriptor: (version >= 2 && (flags & 64) !== 0) ? encoding4_25.decode(state) : null,
      capabilityAdvertisement: (version >= 3 && (flags & 128) !== 0) ? encoding4_26.decode(state) : null
    }
  }
}

// @mesh-contact/capability-descriptor
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.capability)
    c.string.preencode(state, m.methodName)
    c.string.preencode(state, m.dispatchCommand)
    c.string.preencode(state, m.requestEncoding)
    c.string.preencode(state, m.responseEncoding)
    c.string.preencode(state, m.protocolFamily)
    c.string.preencode(state, m.protocolSchema)
    c.string.preencode(state, m.ownerRepo)
    c.string.preencode(state, m.proofScope)
    c.string.preencode(state, m.transportKind)
    c.string.preencode(state, m.contactSeam)
    state.end++ // max flag is 8 so always one byte
  },
  encode(state, m) {
    const flags =
      ((version >= 2 && m.localLayerDefault) ? 1 : 0) |
      ((version >= 2 && m.meshLayerDefault) ? 2 : 0) |
      ((version >= 2 && m.discoveryRequired) ? 4 : 0) |
      ((version >= 2 && m.participantContact) ? 8 : 0)

    c.string.encode(state, m.capability)
    c.string.encode(state, m.methodName)
    c.string.encode(state, m.dispatchCommand)
    c.string.encode(state, m.requestEncoding)
    c.string.encode(state, m.responseEncoding)
    c.string.encode(state, m.protocolFamily)
    c.string.encode(state, m.protocolSchema)
    c.string.encode(state, m.ownerRepo)
    c.string.encode(state, m.proofScope)
    c.string.encode(state, m.transportKind)
    c.string.encode(state, m.contactSeam)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.string.decode(state)
    const r5 = c.string.decode(state)
    const r6 = c.string.decode(state)
    const r7 = c.string.decode(state)
    const r8 = c.string.decode(state)
    const r9 = c.string.decode(state)
    const r10 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      capability: r0,
      methodName: r1,
      dispatchCommand: r2,
      requestEncoding: r3,
      responseEncoding: r4,
      protocolFamily: r5,
      protocolSchema: r6,
      ownerRepo: r7,
      proofScope: r8,
      transportKind: r9,
      contactSeam: r10,
      localLayerDefault: (version >= 2 && (flags & 1) !== 0),
      meshLayerDefault: (version >= 2 && (flags & 2) !== 0),
      discoveryRequired: (version >= 2 && (flags & 4) !== 0),
      participantContact: (version >= 2 && (flags & 8) !== 0)
    }
  }
}

// @mesh-contact/participant-capabilities-request
const encoding6 = {
  preencode(state, m) {
    c.string.preencode(state, m.requestId)
    c.string.preencode(state, m.participant)
  },
  encode(state, m) {
    c.string.encode(state, m.requestId)
    c.string.encode(state, m.participant)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      requestId: r0,
      participant: r1
    }
  }
}

// @mesh-contact/participant-capabilities-response.capabilities
const encoding7_5 = c.array(c.frame(encoding5))

// @mesh-contact/participant-capabilities-response
const encoding7 = {
  preencode(state, m) {
    c.string.preencode(state, m.responseId)
    c.string.preencode(state, m.requestId)
    c.string.preencode(state, m.participant)
    c.string.preencode(state, m.protocolFamily)
    c.string.preencode(state, m.protocolSchema)
    encoding7_5.preencode(state, m.capabilities)
  },
  encode(state, m) {
    c.string.encode(state, m.responseId)
    c.string.encode(state, m.requestId)
    c.string.encode(state, m.participant)
    c.string.encode(state, m.protocolFamily)
    c.string.encode(state, m.protocolSchema)
    encoding7_5.encode(state, m.capabilities)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.string.decode(state)
    const r5 = encoding7_5.decode(state)

    return {
      responseId: r0,
      requestId: r1,
      participant: r2,
      protocolFamily: r3,
      protocolSchema: r4,
      capabilities: r5
    }
  }
}

// @mesh-contact/contact-proof-evidence.capabilityDescriptor, deferred due to recusive use
const encoding4_25 = c.frame(encoding5)
// @mesh-contact/contact-proof-evidence.capabilityAdvertisement, deferred due to recusive use
const encoding4_26 = c.frame(encoding7)

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@mesh-contact/transport-descriptor':
      return encoding0
    case '@mesh-contact/readiness-evidence':
      return encoding1
    case '@mesh-contact/contact-proof-request':
      return encoding2
    case '@mesh-contact/contact-proof-response':
      return encoding3
    case '@mesh-contact/contact-proof-evidence':
      return encoding4
    case '@mesh-contact/capability-descriptor':
      return encoding5
    case '@mesh-contact/participant-capabilities-request':
      return encoding6
    case '@mesh-contact/participant-capabilities-response':
      return encoding7
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
